module.exports = {
  parser: "@babel/eslint-parser",
  plugins: ["@babel"],
  rules: {
    "new-cap": "off",
    "camelcase": "off",
    "no-invalid-this": "off",
    "object-curly-spacing": "off",
    "quotes": "off",
    "semi": "off",
    "no-unused-expressions": "off",
    "valid-typeof": "off",
    "babel/new-cap": "error",
    "babel/camelcase": "error",
    "babel/no-invalid-this": "error",
    "babel/object-curly-spacing": "error",
    "babel/quotes": ["error", "double"],
    "babel/semi": ["error", "always"],
    "babel/no-unused-expressions": "error",
    "babel/valid-typeof": "error",
  },
};
